FROM node:22-alpine

ARG UID=1000
ARG GID=1000

WORKDIR /app

COPY ./src/package.json .

RUN rm -rf node_modules package-lock.json

RUN npm install --legacy-peer-deps

COPY ./src .

EXPOSE 3000

# Run in development mode with hot reload
CMD ["npm", "run", "dev"]
