# Generated by Django 5.2.8 on 2026-01-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
