# Generated by Django 5.2.8 on 2026-01-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipes_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredients',
            name='fdc_id',
            field=models.IntegerField(blank=True, help_text='Food Data Central API ID for nutrition calculation', null=True),
        ),
    ]
