# Generated by Django 5.2.8 on 2026-01-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_update_nutrition_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/'),
        ),
        migrations.AlterField(
            model_name='recipeimages',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
