# Generated by Django 5.2.8 on 2026-01-26 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipes_created_at_alter_recipes_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Recipes'},
        ),
    ]
