# Generated by Django 5.2.8 on 2026-01-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL (optional)', max_length=500, null=True),
        ),
    ]
