# Generated by Django 5.2.8 on 2026-01-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_add_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='published', max_length=20),
        ),
    ]
